version: '3.3'

services:
  quantu-postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - quantu-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  quantu-postgres: