replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 60

image:
  repository: ghcr.io/quantu/quantu/quantu
  pullPolicy: Always
  hash: sha256:2af310fac13872efeed20df46547f19616fecab261e1dd0a23bc63c5b75ad30f

env:
  NODE_ENV: production

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/secure-backends: 'true'
  hosts:
    - host: quantu.app
      paths:
        - /
  tls:
    - secretName: quantu-quantu-tls
      hosts:
        - quantu.app

resources:
  requests:
    cpu: 800m
    memory: 100M
  limits:
    cpu: 1000m
    memory: 1000M

postgresql:
  architecture: replicaset
  replication:
    applicationName: quantu
  auth:
    database: quantu
    username: quantu
    replicationUsername: quantu
  primary:
    persistence:
      enabled: true
      storageClass: linode-block-storage-retain
  rbac:
    create: true